# Set theme
remote_theme: pmarsceill/just-the-docs

# theme: jekyll-theme-cayman

title: AI Forecasting Dictionary
email: hello@parallelforecast.com
description: >- # this means to ignore newlines until "baseurl:"
  a set of standards and conventions for precisely interpreting AI and auxiliary terms.
baseurl: "/AI-dict" # the subpath of your site, e.g. /blog
url: "https://parallel-forecast.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  parallel-forecast
version: v0.3.0

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "AI Resolution Dictionary on GitHub":
    - "//github.com/parallel-forecast/AI-dict"
